--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/laigelplayz/AdminUI
build-by-default: true
branches:
- master
projects:
  AdminUI:
    path: "https://github.com/laigelplayz/AdminUI"
...
