name: AdminUI
version: 0.0.1
main: LaigelPlayz\AdminUI\Main
api: 3.15.0
author: LaigelPlayz

commands:
  adminui:
    description: "Open Admin UI"
    permission: "admin.ui.cmd"
permission:
  admin.ui.cmd:
    description: "permission to use /adminui"
    default: op